spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
#          filters:
#            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: game-service
          uri: http://spacebattle-server:8080
          predicates:
            - Path=/game/**

        - id: command-service
          uri: http://spacebattle-server:8080
          predicates:
            - Path=/command/**
          filters:
            - name: RequestLogger
