name: Java CI for all projects

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Find and build all Maven projects
        run: |
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
            if [ -f "$dir/pom.xml" ]; then
              echo ">>> Building project in $dir"
              mvn -f "$dir/pom.xml" clean verify || exit 1
            fi
          done

      - name: Collect JaCoCo reports
        run: |
          mkdir -p test-results
          find . -type d -name "jacoco" -exec cp -r --parents {} test-results \;
          find . -type d -name "jacoco-aggregate" -exec cp -r --parents {} test-results \;
          find . -type d -name "surefire-reports" -exec cp -r --parents {} test-results \;

      - name: Upload all test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: test-results
